#!/usr/bin/env zsh

STOW_FOLDERS=(personal zsh bin nvim tmux)

pushd "$DOTFILES" || exit 1

for folder in $STOW_FOLDERS; do
  if [[ -d "$folder" ]]; then
    echo "Stowing $folder"
    stow -D "$folder"
    stow "$folder"
  else
    echo "Skipping $folder (not found)"
  fi
done

popd

